import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';
import { buildPalette, DEFAULT_SEED, DEFAULT_VARIANT } from '../src/theme/palette.js';


const OPEN = '/* >>> generated by scripts/generateTheme.js — do not edit by hand */';
const CLOSE = '/* <<< end generated */';

const cssPath = join(process.cwd(), 'src', 'globals.css');

const block = (selector, mode, indent) => {
    const body = Object.entries(buildPalette(DEFAULT_SEED, mode, DEFAULT_VARIANT))
        .map(([token, hex]) => `${indent}    ${token}: ${hex};`)
        .join('\n');
    return `${indent}${selector} {\n${body}\n${indent}}`;
};

const generated = [
    OPEN,
    `/* seed: ${DEFAULT_SEED} · variant: ${DEFAULT_VARIANT} — regenerate with \`npm run theme\` */`,
    block(':root', 'light', ''),
    '',
    block('[data-theme="dark"]', 'dark', ''),
    '',
    '@media (prefers-color-scheme: dark) {',
    block(':root:not([data-theme="light"])', 'dark', '    '),
    '}',
    CLOSE,
].join('\n');

const css = readFileSync(cssPath, 'utf8');
const start = css.indexOf(OPEN);
const end = css.indexOf(CLOSE);

if (start === -1 || end === -1) {
    console.error(`[mott-design-components] no encontre los marcadores en ${cssPath}`);
    process.exit(1);
}

writeFileSync(cssPath, css.slice(0, start) + generated + css.slice(end + CLOSE.length));

const count = Object.keys(buildPalette(DEFAULT_SEED, 'light', DEFAULT_VARIANT)).length;
console.log(`[mott-design-components] globals.css actualizado: ${count} tokens x 2 temas (seed ${DEFAULT_SEED}, variante ${DEFAULT_VARIANT})`);
